import React from 'react';

const ArcxStaking: React.FC = () => {
  return (
    <div id="arcx-staking" className="w-full h-full flex flex-col items-center justify-center p-8 md:p-16 bg-adam-dark overflow-hidden">
      <div className="text-center w-full max-w-7xl mx-auto mb-12 animate-fade-in-down">
        <h2 className="text-4xl md:text-6xl font-thin text-gray-200 tracking-[0.2em] uppercase">
          Liquid <span className="text-arcx-orange">Staking</span>
        </h2>
        <p className="mt-4 text-gray-400 font-light max-w-2xl mx-auto">
          Stake your ARCx to receive sARCx, a liquid derivative that represents your share of governance power and rewards.
        </p>
      </div>

      <div className="w-full max-w-4xl grid grid-cols-1 md:grid-cols-5 gap-8 items-center">
        {/* SVG Diagram */}
        <div className="md:col-span-3 w-full h-64 relative">
          <svg width="100%" height="100%" viewBox="0 0 500 150">
            <defs>
              <linearGradient id="flow-grad" x1="0%" y1="0%" x2="100%" y2="0%">
                <stop offset="0%" stopColor="#f97316" stopOpacity="0" />
                <stop offset="50%" stopColor="#f97316" />
                <stop offset="100%" stopColor="#f97316" stopOpacity="0" />
              </linearGradient>
              <style>{`
                .flow-line {
                  stroke-dasharray: 5 5;
                  animation: flow-anim 2s linear infinite;
                }
                @keyframes flow-anim {
                  from { stroke-dashoffset: 20; }
                  to { stroke-dashoffset: 0; }
                }
              `}</style>
            </defs>

            {/* ARCx Token */}
            <g className="animate-fade-in" style={{animationDelay: '0.3s'}}>
              <rect x="20" y="50" width="100" height="50" rx="5" fill="#11131a" stroke="#4a4a4a" />
              <text x="70" y="80" fill="#f97316" textAnchor="middle" className="font-mono text-xl">ARCx</text>
            </g>

            {/* Staking Contract */}
            <g className="animate-fade-in" style={{animationDelay: '0.6s'}}>
              <rect x="200" y="25" width="100" height="100" rx="5" fill="#11131a" stroke="#f97316" />
              <text x="250" y="70" fill="#a0a0a0" textAnchor="middle" className="font-mono text-sm">Staking</text>
              <text x="250" y="90" fill="#a0a0a0" textAnchor="middle" className="font-mono text-sm">Contract</text>
            </g>

            {/* sARCx Token */}
            <g className="animate-fade-in" style={{animationDelay: '0.9s'}}>
              <rect x="380" y="50" width="100" height="50" rx="5" fill="#11131a" stroke="#4a4a4a" />
              <text x="430" y="80" fill="#fdba74" textAnchor="middle" className="font-mono text-xl">sARCx</text>
            </g>

            {/* Flow Lines */}
            <g style={{animationDelay: '1.2s'}} className="animate-fade-in">
                <path d="M 120 75 H 200" stroke="url(#flow-grad)" strokeWidth="1" fill="none" className="flow-line" />
                <path d="M 300 75 H 380" stroke="url(#flow-grad)" strokeWidth="1" fill="none" className="flow-line" />
            </g>

          </svg>
        </div>

        {/* Benefits List */}
        <div className="md:col-span-2 text-gray-300 animate-fade-in-right" style={{animationDelay: '1.5s'}}>
            <ul className="space-y-4">
                <li className="flex items-start">
                    <svg className="w-5 h-5 text-arcx-orange mr-3 mt-1 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                    <span className="font-light text-sm">
                        <strong className="font-normal text-gray-200">Governance Power:</strong> Use sARCx to vote on ADAM Protocol proposals.
                    </span>
                </li>
                <li className="flex items-start">
                    <svg className="w-5 h-5 text-arcx-orange mr-3 mt-1 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                    <span className="font-light text-sm">
                        <strong className="font-normal text-gray-200">Ecosystem Yield:</strong> Earn rewards generated by the protocol and ecosystem partners.
                    </span>
                </li>
                <li className="flex items-start">
                    <svg className="w-5 h-5 text-arcx-orange mr-3 mt-1 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                    <span className="font-light text-sm">
                        <strong className="font-normal text-gray-200">DeFi Composability:</strong> sARCx is a standard ERC-20 token that can be used across DeFi while still earning rewards.
                    </span>
                </li>
            </ul>
        </div>
      </div>
    </div>
  );
};

export default ArcxStaking;